#!/bin/bash
#
# Copyright © 2014 Jesse 'Jeaye' Wilkerson
# See licensing in LICENSE file, or at:
#   http://www.opensource.org/licenses/MIT
#
# File: do_install
# Author: Jesse 'Jeaye' Wilkerson

# XXX: Do not call this script directly: use `make install`
set -o errexit
set -o nounset

if [[ $# == 0 ]];
then
  echo "error: Use \`make install\` to install"
  exit 1
fi

UNINSTALL=0
if [[ $# == 1 && "$1" = "undo" ]];
then
  UNINSTALL=1
  echo "Uninstalling from $datarootdir"
else
  echo "Installing from $PWD to $datarootdir"
fi

mkdir -p $datarootdir
for file in "$PWD"/src/*.hpp ; do
  out=$datarootdir/$(basename "$file");

  if [ $UNINSTALL -eq 1 ];
  then
    rm -f "$out";
  else
    install -m 0644 "$file" "$out";
  fi
done

if [ $UNINSTALL -eq 1 ];
then
  rmdir "$datarootdir"
fi
echo "Done"
